stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - git submodule update --init --recursive
# ----------------------------------------------------------
# Linux Native Build
# ----------------------------------------------------------
linux-build:
  stage: build
  image: luftd/knx-ci:latest
  script:
    - cmake --preset=linux-debug-gcc
    - cmake --build out/build/linux-debug-gcc
  artifacts:
    paths:
      - out/build/linux-debug-gcc
    expire_in: 1 week

# ----------------------------------------------------------
# Windows (Cross-compile with MinGW-w64)
# ----------------------------------------------------------
windows-cross-build:
  stage: build
  image: luftd/mingw-cross:latest
  cache:
    key: "wxwidgets-windows-cross-11-2025"
    policy: pull-push
    paths:
      - out/build/windows-cross-release/_deps/wxwidgets-src
      - out/build/windows-cross-release/_deps/wxwidgets-build
  script:
    - cmake --preset=windows-cross-release
    - cmake --build out/build/windows-cross-release
  artifacts:
    paths:
      - out/build/windows-cross-release/eitt_virtual_gui.exe
      - out/build/windows-cross-release/lssb_virtual_gui.exe
      - out/build/windows-cross-release/lsab_virtual_gui.exe
      - out/build/windows-cross-release/inverter_virtual_gui.exe
      - out/build/windows-cross-release/cem_virtual_gui.exe
      - out/build/windows-cross-release/charger_virtual_gui.exe
    expire_in: 1 week