stages:
  - build_linux_debug_gcc
  - lint_linux_debug

variables:
  BUILD_DIR: out/build/linux-debug-gcc

before_script:
  - git submodule update --init --recursive

build_linux_debug_gcc:
  stage: build_linux_debug_gcc
  image: luftd/knx-ci:latest
  script:
    - cmake --preset linux-debug-gcc
    - cmake --build $BUILD_DIR
  artifacts:
    paths:
      - $BUILD_DIR/
    expire_in: 1 week

lint:
  stage: lint
  image: luftd/knx-ci:latest
  script:
    - cmake --preset linux-debug-gcc
    - cmake --build $BUILD_DIR
    - ninja -C $BUILD_DIR tidy || true
  artifacts:
    when: always
    paths:
      - $BUILD_DIR/
    expire_in: 1 week
