[tool.poetry]
name = "knxiotclient"
version = "0.1.0"
description = "KNX IoT Client Example"
authors = ["Oskar Camenzind <oskar.camenzind@siemens.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10.0,<=3.12.3"
click = "^8.1.7"
zeroconf = "^0.132.2"
aiocoap = {extras = ["oscore"], version = "^0.4.11"}
cbor2 = "^5.6.5"
pycryptodome = "^3.20.0"
ecdsa = "^0.19.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pylint = "^3.3.6"

[tool.poetry.scripts]
knxiotclient = "knxiotclient.cli:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
