"""
Offline SPAKE2+ registration-record generator for KNX IoT (RFC 9383 sec. 3.2).

Derives the precalculated registration record (w0, L = w1*G, salt) for a fixed
device password so the device (Verifier) never needs the plaintext password
online. Emits ready-to-paste C byte arrays and verifies the record by running a
full mutual SPAKE2+ handshake: the prover side uses the password-derived w1 and
the verifier side uses only the stored L. If both derive the same K_main, the
record is correct.

Run:
    python tests/runtime/gen_spake_record.py
"""

import hashlib

from knx_spake2plus import (
    M_POINT,
    N_POINT,
    P256_ORDER,
    Spake2PlusClient,
    _ec_scalar_mult,
    _encode_point,
    _encode_string,
    _encode_w0_mpi,
    _p256_point_add,
    _p256_point_sub,
    _p256_scalar_mult,
    CONTEXT,
    ID_PROVER,
    ID_VERIFIER,
)

# ----------------------------------------------------------------------------
# Inputs that define the registration record
# ----------------------------------------------------------------------------

# Device password (NOT used online by the device; kept for the demo UI/QR only).
PASSWORD = "2X4W3TE0DFLLS19Y1FCH"

# Fixed device-specific PBKDF2 salt (32 bytes). KNX 3.6.6.2: 16..32 bytes.
SALT = bytes.fromhex(
    "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
)

# Iteration count, stored as part of the registration record (oc_spake_record_t.it).
ITERATIONS = 50000

# P-256 base point G (uncompressed).
G_POINT = bytes.fromhex(
    "04"
    "6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296"
    "4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5"
)


def _derive_record(password: str, salt: bytes, iterations: int):
    """Derive (w0, w1, L) using the same PBKDF2 path as the C stack."""
    client = Spake2PlusClient(password=password)
    client.salt = salt
    client.iterations = iterations
    client._derive_w0_w1()
    w0 = client.w0
    w1 = client.w1
    w1_int = int.from_bytes(w1, "big")
    L = _p256_scalar_mult(w1_int, G_POINT)  # L = w1 * G
    return w0, w1, L


def _format_c_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        body = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {body},")
    lines.append("};")
    return "\n".join(lines)


def _verify_record(password, salt, iterations, w0, w1, L) -> bytes:
    """
    Run a full mutual SPAKE2+ handshake. Prover uses w1; verifier uses only L.
    Returns the shared K_main if both sides agree (raises otherwise).
    """
    w0_int = int.from_bytes(w0, "big")
    w1_int = int.from_bytes(w1, "big")

    # Prover (initiator): x random, shareP = x*G + w0*M
    x_priv = 0x1122334455667788990011223344556677889900112233445566778899001122 % P256_ORDER
    pub_x = _p256_scalar_mult(x_priv, G_POINT)
    shareP = _p256_point_add(pub_x, _p256_scalar_mult(w0_int, M_POINT))

    # Verifier (responder): y random, shareV = y*G + w0*N
    y_priv = 0x00AABBCCDDEEFF00112233445566778899AABBCCDDEEFF00112233445566778899 % P256_ORDER
    pub_y = _p256_scalar_mult(y_priv, G_POINT)
    shareV = _p256_point_add(pub_y, _p256_scalar_mult(w0_int, N_POINT))

    # Verifier computes Z, V using stored L (no w1).
    base_v = _p256_point_sub(shareP, _p256_scalar_mult(w0_int, M_POINT))  # = pub_x
    Z_v = _p256_scalar_mult(y_priv, base_v)
    V_v = _p256_scalar_mult(y_priv, L)

    # Prover computes Z, V using password-derived w1.
    base_p = _p256_point_sub(shareV, _p256_scalar_mult(w0_int, N_POINT))  # = pub_y
    Z_p = _p256_scalar_mult(x_priv, base_p)
    V_p = _p256_scalar_mult(w1_int, base_p)

    assert Z_v == Z_p, "Z mismatch: verifier/prover disagree"
    assert V_v == V_p, "V mismatch: stored L is not consistent with w1*G"

    def transcript(Z, V):
        tt = b""
        tt += _encode_string(CONTEXT)
        tt += _encode_string(ID_PROVER)
        tt += _encode_string(ID_VERIFIER)
        tt += _encode_point(M_POINT)
        tt += _encode_point(N_POINT)
        tt += _encode_point(shareP)
        tt += _encode_point(shareV)
        tt += _encode_point(Z)
        tt += _encode_point(V)
        tt += _encode_w0_mpi(w0)
        return hashlib.sha256(tt).digest()

    k_main_v = transcript(Z_v, V_v)
    k_main_p = transcript(Z_p, V_p)
    assert k_main_v == k_main_p, "K_main mismatch"
    return k_main_v


def main():
    w0, w1, L = _derive_record(PASSWORD, SALT, ITERATIONS)
    k_main = _verify_record(PASSWORD, SALT, ITERATIONS, w0, w1, L)

    print("/*")
    print("  Precalculated SPAKE2+ offline registration record (RFC 9383 sec. 3.2).")
    print(f"  Password : {PASSWORD}")
    print(f"  Salt     : {SALT.hex()}")
    print(f"  Iterations (record field .it): {ITERATIONS}")
    print("  Generated by tests/runtime/gen_spake_record.py")
    print("*/")
    print(_format_c_array("g_spake_w0", w0))
    print(_format_c_array("g_spake_L", L))
    print(_format_c_array("g_spake_salt", SALT))
    print(f"static const uint32_t g_spake_it = {ITERATIONS};")
    print()
    print(f"// verification K_main = {k_main.hex()}")
    print(f"// len(w0) full bytes = {len(w0)}, stripped = {len(w0.lstrip(chr(0).encode()))}")


if __name__ == "__main__":
    main()
