@startuml

title Porting Layer 

component [Application]
component [Stack]
component [Platform]

note bottom of Platform 
 Clock, Secure Storage, PRNG, Media Connectivity
end note 

note right of Platform
 Existing ports Linux, Windows
end note 

Application -> Stack
Stack -> Platform


@enduml