@startuml

title Stack Components 


database Stack as "
Application
----
m/o Resources (vendor specific)
----
OSCORE (RFC 8613)
----
Core-Link (RFC 6690) | CBOR (RFC 7049)
----
CoAP (RFC 7252)
----
mDNS (RFC 6762) | DTLS (RFC 4347)
----
UDP (RFC 768)
----
IPv6 (RFC 2460)
----
Porting Layer (vendor/platform specific)
----
WiFi | Thread | Ethernet | ...
"

@enduml